// <auto-generated />
namespace WoMU_lab1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class boo1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(boo1));
        
        string IMigrationMetadata.Id
        {
            get { return "201602021714203_boo1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
